###
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "nana",
    "email":"nanazinha@gmail.com",
    "senha":"123"
}

###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome": "mamama",
    "email":"nana@gmail.com",
    "senha": "133"
   } 

###
DELETE http://localhost:3000/usuarios/

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"nanazinha@gmail.com",
    "senha":"123"
}

