###
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "nanaja",
    "senha": "2011"
}

###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome": "regina",
    "senha": "gabriela"
}
